DROP DATABASE IF EXISTS drink_db;
CREATE DATABASE drink_db;

USE drink_db;

CREATE TABLE drinks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  drink VARCHAR(100) NOT NULL,
  imbibed BOOLEAN DEFAULT FALSE
);
